=== 00mjk/HPCC-Platform/initfiles/componentfiles/configschema/templates/schema/ModTemplateSchema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Schema for validating environment modification template",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description" : "Name for the template"
        },
        "description": {
            "type": "string",
            "description" : "A description of the template"
        },
        "type": {
            "type": "string",
            "enum": [
                "new",
                "modification"
            ],
            "description" : "Type of template. Mainly used for filtering templates."
        },
        "variables": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description" : "Name of the variable to which the input is assigned. This value is available using {{name}} anywhere in the template"
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "string",
                            "iprange",
                            "ipaddress",
                            "hostname"
                        ],
                        "description" : "The variable type."
                    },
                    "prompt": {
                        "type": "string",
                        "description" : "String shown to user during interactive input"
                    },
                    "description": {
                        "type": "string",
                        "description" : "Description of what this value represents in the template."
                    },
                    "values": {
                        "type": "array",
                        "items" : {
                            "type" : "string"
                        },
                        "description" : "Pre-assigned values"
                    },
                    "user_input": {
                        "type": "boolean",
                        "description" : "Set to true if user must input this value(s) (defaults to true)",
                        "default" : true
                    },
                    "prepared_value": {
                        "type": "string",
                        "description" : "Optional. Used to prepare the final value for use during template execution. Usually combined with other variable values of the form {{varname}}"
                    }
                },
                "required": [
                    "name",
                    "type"
                ]
            },
            "description" : "Array of variables for template execution. Some may require user input."
        },
        "operations": {
            "type": "array",
            "minItems": 0,
            "items": {
                "$ref": "#/definitions/operation"
            }
        }
    },
    "required": [
        "name",
        "type",
        "operations"
    ],
    "definitions": {
        "operation": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "action": {
                    "type" : "string",
                    "enum": [
                        "create_node",
                        "modify_node",
                        "find_node",
                        "delete_node"
                    ],
                    "description" : "Action to perform for this operation"
                },
                "parent_path": {
                    "type": "string"
                },
                "parent_nodeid": {
                    "type": "string"
                }
            },
            "allOf": [
                {
                    "oneOf": [
                        {
                            "properties": {
                                "action": {
                                    "enum": [
                                        "create_node"
                                    ]
                                },
                                "data": {
                                    "$ref": "#/definitions/create_data_info"
                                }
                            },
                            "required": [
                                "action",
                                "data"
                            ]
                        },
                        {
                            "properties": {
                                "action": {
                                    "enum": [
                                        "modify_node"
                                    ]
                                },
                                "data": {
                                    "$ref": "#/definitions/modify_data_info"
                                }
                            },
                            "required": [
                                "action",
                                "data"
                            ]
                        },
                        {
                            "properties": {
                                "action": {
                                    "enum": [
                                        "find_node"
                                    ]
                                },
                                "data": {
                                    "$ref": "#/definitions/find_data_info"
                                }
                            },
                            "required": [
                                "action"
                            ]
                        },
                        {
                            "properties": {
                                "action": {
                                    "enum": [
                                        "delete_node"
                                    ]
                                },
                                "data": {
                                    "$ref": "#/definitions/delete_data_info"
                                }
                            },
                            "required": [
                                "action"
                            ]
                        }
                    ]
                },
                {
                    "oneOf": [
                        {
                            "required": [
                                "parent_path"
                            ]
                        },
                        {
                            "required": [
                                "parent_nodeid"
                            ]
                        }
                    ]
                }
            ],
            "description" : "Definition of the operation to perform"
        },
        "create_data_info": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "string"
                },
                "start_index": {
                    "type": "string"
                },
                "node_type": {
                    "type": "string"
                },
                "save_nodeid": {
                    "$ref": "#/definitions/save_info"
                },
                "attributes": {
                    "$ref": "#/definitions/attribute_values"
                }
            },
            "allOf": [
                {
                    "required": [
                        "node_type"
                    ]
                }
            ]
        },
        "modify_data_info": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "string"
                },
                "start_index": {
                    "type": "string"
                },
                "save_nodeid": {
                    "$ref": "#/definitions/save_info"
                },
                "attributes": {
                    "$ref": "#/definitions/attribute_values"
                }
            },
            "allOf": [
                {
                    "required": [
                        "attributes"
                    ]
                }
            ]
        },
        "find_data_info": {
            "type": "object",
            "properties": {
                "node_type": {
                    "type": "string"
                },
                "save_nodeid": {
                    "$ref": "#/definitions/save_info"
                },
                "error_if_not_found": {
                    "type": "boolean",
                    "default" : true
                },
                "create_if_not_found": {
                    "type": "boolean",
                    "default" : false
                },
                "attributes": {
                    "$ref": "#/definitions/attribute_refs"
                }
            }
        },
        "delete_data_info": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "string"
                },
                "start_index": {
                    "type": "string"
                },
                "error_if_not_found": {
                    "type": "boolean",
                    "default" : true
                }
            }
        },
        "attribute_value": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "save_value": {
                    "$ref": "#/definitions/save_info"
                },
                "do_not_set": {
                    "type": "boolean"
                },
                "error_if_not_found" : {
                    "type" : "boolean",
                    "default" : false,
                    "description" : "Used for actions that are looking for the presence of the attribute"
                }
            },
            "required": [
                "name",
                "value"
            ],
            "not" : {
                "required" : ["first_of"]
            }
        },
        "attribute_values": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/attribute_value"
            }
        },
        "attribute_ref" : {
            "type": "object",
            "properties": {
                "first_of" : {
                    "type" : "array",
                    "items" : {
                        "type" : "string"
                    },
                    "description" : "Finds the first attribute from the array of names"
                },
                "name": {
                    "type": "string"
                },
                "save_value": {
                    "$ref": "#/definitions/save_info"
                },
                "error_if_not_found" : {
                    "type" : "boolean",
                    "default" : false,
                    "description" : "Used for actions that are looking for the presence of the attribute"
                },
                "error_if_empty" : {
                    "type" : "boolean",
                    "default" : false,
                    "description" : "Requires the attribute to be present and have a value (one of first of also)"
                }
            },
            "oneOf": [
                {
                    "required": [
                        "name"
                    ]
                },
                {
                    "required" : [
                        "first_of"
                    ]
                }
            ]
        },
        "attribute_refs": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/attribute_ref"
            }
        },
        "save_info": {
            "type": "object",
            "properties": {
                "save_name": {
                    "type": "string"
                },
                "duplicate_ok": {
                    "type": "boolean"
                }
            },
            "required": [
                "save_name"
            ]
        }
    }
}

=== 00mjk/HPCC-Platform/testing/unittests/configmgr/templates/OperationsTest2.json
{
    "name" : "",
    "type" : "modification",
    "description" : "Test allowing duplicate save node ID names, should execute w/o error",
    "variables" : [
    ],
    "operations" : [
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child1",
            "data" : {
                "save_nodeid" : {
                    "save_name" : "nodes"
                }
            }
        },
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child2",
            "data" : {
                "save_nodeid" : {
                    "save_name" : "nodes",
                    "duplicate_ok" : true
                }
            }
        }
    ]
}

=== 00mjk/HPCC-Platform/testing/unittests/configmgr/templates/OperationsTest5.json
{
    "name" : "",
    "type" : "modification",
    "description" : "Test not allowing duplicate save of attribute values, should cause an error",
    "variables" : [
    ],
    "operations" : [
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child1/SubChild1",
            "data" : {
                "attributes" : [
                    {
                        "name" : "attr1",
                        "save_value" : {
                            "save_name" : "attrvalue"
                        }
                    }
                ]
            }
        },
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child2/SubChild2",
            "data" : {
                "attributes" : [
                    {
                        "name" : "attr1",
                        "save_value" : {
                            "save_name" : "attrvalue",
                            "duplicate_ok" : false
                        }
                    }
                ]
            }
        }
    ]
}

=== 00mjk/HPCC-Platform/testing/unittests/configmgr/templates/FindNodeTest1.json
{
    "name" : "Find nodes test 1",
    "type" : "modification",
    "description" : "Finds a node that exists",
    "variables" : [
        {
            "name" : "child",
            "values" : ["SubChild1"],
            "type" : "string"
        },
        {
            "name" : "ipaddresses",
            "type" : "ipaddress"
        }
    ],
    "operations" : [
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child1/{{child}}",
            "data" : {
                "save_nodeid" : {
                    "save_name" : "parent1"
                }
            }
        },
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child1/SubChild1[@attr1='child1_subchild1_2']"
        },
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child2"
        },
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child3",
            "data" : {
                "error_if_not_found" : false
            }
        },
        {
            "action" : "modify_node",
            "parent_nodeid" : "{{parent1}}",
            "data" : {
                "attributes" : [
                    {
                        "name" : "attr2",
                        "value" : "4"
                    }
                ]
            }
        },
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child1/SubChild1[@attr2='4']"
        },
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child1/SubChild1",
            "data" : {
                "attributes" : [
                    {
                        "first_of" : ["attr2", "attr1"],
                        "save_value" : {
                            "save_name" : "fn2"
                        }
                    }
                ]
            }
        }
    ]
}

=== 00mjk/HPCC-Platform/testing/unittests/configmgr/templates/OperationsTest4.json
{
    "name" : "",
    "type" : "modification",
    "description" : "Test allowing duplicate save of attribute values, should execute w/o error",
    "variables" : [
    ],
    "operations" : [
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child1/SubChild1",
            "data" : {
                "attributes" : [
                    {
                        "name" : "attr1",
                        "save_value" : {
                            "save_name" : "attrvalue"
                        }
                    }
                ]
            }
        },
        {
            "action" : "find_node",
            "parent_path" : "/Root/Child2/SubChild2",
            "data" : {
                "attributes" : [
                    {
                        "name" : "attr1",
                        "save_value" : {
                            "save_name" : "attrvalue",
                            "duplicate_ok" : true
                        }
                    }
                ]
            }
        }
    ]
}
